#!/usr/bin/env python3
"""LOMPOC VALLEY FLORIST — Homecoming corsages. A broadcast-style local TV spot for a Growth member.
Their own photos (from their Instagram carousel, cropped off their baked-in text so our typography
leads), both school badges, and the two Homecoming dates they announced:
  Cabrillo Homecoming — Sat Oct 3 (their home game is Fri Oct 2 vs Morro Bay at Huyck)
  Lompoc Homecoming   — Sat Oct 24 (their home game is Fri Oct 23 vs Atascadero at Huyck)
17.0 s, 9:16. Arthur announcer read, elegant bed. Generated by: python3 gen.py
"""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
X = 0.30
SCENES = [("s1-open", 0.00, 2.60), ("s2-dates", 2.40, 4.40), ("s3-craft", 6.60, 5.60), ("s4-cta", 12.00, 5.00)]
TOTAL = 17.00
VO_START = 0.60; VO_DUR = 14.80
SUBS = [
    (0.60, 2.28,  "Homecoming is coming."),
    (2.55, 4.35,  "Cabrillo, October 3rd."),
    (4.61, 6.60,  "Lompoc, October 24th."),
    (7.06, 11.98, "Corsages and boutonnières, handmade in Lompoc since 1976."),
    (12.33, 15.15, "Order yours early, at Lompoc Valley Florist."),
]
GOLD = "#efc618"; INK = "#241629"; PURPLE = "#650c75"; BG = "#140a17"; CREAM = "#fdfaf4"

def css(cid):
    return f"""
      [data-composition-id="{cid}"] .stage {{ position:absolute; inset:0; opacity:0; will-change:opacity; }}
      [data-composition-id="{cid}"] .wrap {{ position:absolute; inset:0; overflow:hidden; will-change:transform; transform-origin:50% 50%; }}
      [data-composition-id="{cid}"] .cover {{ position:absolute; inset:0; width:100%; height:100%; object-fit:cover; display:block; }}
      [data-composition-id="{cid}"] .vig {{ position:absolute; inset:0; z-index:30; pointer-events:none; background:radial-gradient(ellipse 100% 82% at 50% 45%, rgba(20,10,23,0) 58%, rgba(20,10,23,0.55) 100%); }}
      [data-composition-id="{cid}"] .scrim {{ position:absolute; inset:0; z-index:31; pointer-events:none; background:linear-gradient(to top, rgba(20,10,23,0.93) 0%, rgba(20,10,23,0.55) 34%, rgba(20,10,23,0.05) 66%); }}
      [data-composition-id="{cid}"] .topscrim {{ position:absolute; inset:0; z-index:31; pointer-events:none; background:linear-gradient(to bottom, rgba(20,10,23,0.72) 0%, rgba(20,10,23,0.18) 24%, rgba(20,10,23,0) 40%); }}
      [data-composition-id="{cid}"] .grain {{ position:absolute; inset:0; pointer-events:none; opacity:0.06; z-index:50; background-image:url("data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 width=%27200%27 height=%27200%27%3E%3Cfilter id=%27n%27%3E%3CfeTurbulence type=%27fractalNoise%27 baseFrequency=%270.9%27 numOctaves=%272%27/%3E%3C/filter%3E%3Crect width=%27200%27 height=%27200%27 filter=%27url(%23n)%27 opacity=%271%27/%3E%3C/svg%3E"); }}
      /* client logo bug, our mark as the presenter */
      [data-composition-id="{cid}"] .bug {{ position:absolute; top:142px; left:84px; height:104px; width:auto; z-index:45; filter:drop-shadow(0 6px 18px rgba(0,0,0,0.55)); }}
      [data-composition-id="{cid}"] .mark {{ position:absolute; top:152px; right:84px; width:80px; height:auto; z-index:45; opacity:0.85; }}
      /* broadcast lower third */
      [data-composition-id="{cid}"] .lt {{ position:absolute; left:84px; right:84px; bottom:430px; z-index:40; }}
      [data-composition-id="{cid}"] .lt .bar {{ display:inline-block; background:{GOLD}; color:{INK}; font-weight:800; font-size:28px; letter-spacing:5px; text-transform:uppercase; padding:11px 22px; border-radius:6px; }}
      [data-composition-id="{cid}"] .lt .big {{ display:block; margin-top:18px; color:#fff; font-weight:800; font-size:92px; line-height:0.98; letter-spacing:-3px; text-shadow:0 8px 32px rgba(20,10,23,0.8); }}
      [data-composition-id="{cid}"] .lt .sm {{ display:block; margin-top:14px; color:rgba(253,250,244,0.9); font-weight:600; font-size:36px; }}
      /* date rows */
      [data-composition-id="{cid}"] .drow {{ display:flex; align-items:center; gap:28px; opacity:0; will-change:transform,opacity; }}
      [data-composition-id="{cid}"] .drow img {{ width:150px; height:auto; filter:drop-shadow(0 8px 20px rgba(0,0,0,0.55)); }}
      [data-composition-id="{cid}"] .drow .school {{ color:rgba(253,250,244,0.72); font-weight:800; font-size:30px; letter-spacing:5px; text-transform:uppercase; }}
      [data-composition-id="{cid}"] .drow .date {{ display:block; margin-top:6px; color:#fff; font-weight:800; font-size:70px; letter-spacing:-2px; line-height:1 }}
    """

def wrap(cid, dur, inner, js, first=False, bug=True):
    fade = (f'tl.set("#{cid}-stage", {{ autoAlpha:1 }}, 0);' if first
            else f'tl.fromTo("#{cid}-stage", {{ autoAlpha:0 }}, {{ autoAlpha:1, duration:{X}, ease:"power1.inOut" }}, 0);')
    bug_html = '<img class="bug" src="public/logo-florist.png" alt="Lompoc Valley Florist" />' if bug else ""
    return f'''<template>
  <div data-composition-id="{cid}" data-width="1080" data-height="1920" data-duration="{dur:.2f}" style="position:absolute; inset:0; overflow:hidden; background:{BG if first else 'transparent'}">
    <style>{css(cid)}
    </style>
    <div class="stage" id="{cid}-stage"{' style="opacity:1"' if first else ''}>
      {inner}
      <div class="vig"></div>
    </div>
    {bug_html}
    <img class="mark" src="public/mark-white.png" alt="" />
    <div class="grain"></div>
    <script>
      (() => {{
        const tl = gsap.timeline({{ paused:true, defaults:{{ ease:"power3.out", duration:0.5 }} }});
        {fade}
        {js}
        tl.set({{}}, {{}}, {dur:.2f});
        window.__timelines["{cid}"] = tl;
      }})();
    </script>
  </div>
</template>
'''

def kenburns(cid, img, dur, from_s=1.0, to_s=1.10, pos="50% 50%"):
    return (f'<div class="wrap" id="{cid}-w" data-layout-allow-overflow><img class="cover" src="public/{img}" alt="" style="object-position:{pos}" /></div>',
            f'tl.fromTo("#{cid}-w", {{ scale:{from_s} }}, {{ scale:{to_s}, duration:{dur:.2f}, ease:"none" }}, 0);')

def scene_html(cid, dur):
    if cid == "s1-open":
        media, mjs = kenburns(cid, "p-row.jpg", dur, 1.0, 1.09, "50% 46%")
        inner = f'''{media}
      <div class="scrim"></div><div class="topscrim"></div>
      <div class="lt">
        <span class="bar" id="{cid}-bar" style="opacity:1">Homecoming 2026</span>
        <span class="big" id="{cid}-h" style="opacity:1">Flowers for<br />the big night.</span>
      </div>'''
        return wrap(cid, dur, inner, mjs, first=True)
    if cid == "s2-dates":
        inner = f'''<div style="position:absolute; inset:0; background:linear-gradient(160deg,{PURPLE} 0%, #34063f 55%, {BG} 100%)"></div>
      <div style="position:absolute; left:84px; right:84px; top:31%; z-index:40">
        <span class="bar" id="{cid}-bar" style="display:inline-block; background:{GOLD}; color:{INK}; font-weight:800; font-size:28px; letter-spacing:5px; text-transform:uppercase; padding:11px 22px; border-radius:6px; opacity:0">Mark your calendar</span>
        <div class="drow" id="{cid}-d1" style="margin-top:56px">
          <img src="public/badge-conqs.png" alt="Cabrillo" />
          <div><span class="school">Cabrillo Homecoming</span><span class="date">Sat · Oct 3</span></div>
        </div>
        <div class="drow" id="{cid}-d2" style="margin-top:52px">
          <img src="public/badge-braves.png" alt="Lompoc" />
          <div><span class="school">Lompoc Homecoming</span><span class="date">Sat · Oct 24</span></div>
        </div>
      </div>'''
        js = (f'tl.fromTo("#{cid}-bar", {{ autoAlpha:0, y:-10 }}, {{ autoAlpha:1, y:0, duration:0.35 }}, 0.05);'
              f'tl.fromTo("#{cid}-d1", {{ autoAlpha:0, x:-34 }}, {{ autoAlpha:1, x:0, duration:0.5, ease:"expo.out" }}, 0.30);'
              f'tl.fromTo("#{cid}-d2", {{ autoAlpha:0, x:-34 }}, {{ autoAlpha:1, x:0, duration:0.5, ease:"expo.out" }}, 2.20);')
        return wrap(cid, dur, inner, js)
    if cid == "s3-craft":
        inner = f'''<div class="wrap" id="{cid}-wA" data-layout-allow-overflow><img class="cover" src="public/p-bout.jpg" alt="" style="object-position:50% 50%" /></div>
      <div class="wrap" id="{cid}-wB" data-layout-allow-overflow style="opacity:0"><img class="cover" src="public/p-green.jpg" alt="" style="object-position:50% 50%" /></div>
      <div class="scrim"></div><div class="topscrim"></div>
      <div class="lt" style="bottom:560px">
        <span class="bar" id="{cid}-bar" style="opacity:0">Since 1976</span>
        <span class="big" id="{cid}-h" style="font-size:78px; opacity:0">Corsages &amp;<br />boutonnières,<br />made by hand.</span>
      </div>'''
        js = (f'tl.fromTo("#{cid}-wA", {{ scale:1.0 }}, {{ scale:1.10, duration:{dur:.2f}, ease:"none" }}, 0);'
              f'tl.fromTo("#{cid}-wB", {{ scale:1.04 }}, {{ scale:1.12, duration:{dur:.2f}, ease:"none" }}, 0);'
              f'tl.to("#{cid}-wB", {{ autoAlpha:1, duration:0.55, ease:"power1.inOut" }}, 2.95);'
              f'tl.fromTo("#{cid}-bar", {{ autoAlpha:0, y:-8 }}, {{ autoAlpha:1, y:0, duration:0.32 }}, 0.20);'
              f'tl.fromTo("#{cid}-h", {{ autoAlpha:0, y:18 }}, {{ autoAlpha:1, y:0, duration:0.45, ease:"expo.out" }}, 0.40);')
        return wrap(cid, dur, inner, js)
    if cid == "s4-cta":
        inner = f'''<div style="position:absolute; inset:0; background:linear-gradient(180deg,#fdfaf4 0%, #f3e9dc 100%)"></div>
      <div style="position:absolute; left:0; right:0; top:26%; z-index:40; text-align:center">
        <img id="{cid}-logo" src="public/logo-florist.png" alt="Lompoc Valley Florist" style="width:640px; height:auto; opacity:0" />
        <span id="{cid}-cta" style="display:block; width:fit-content; margin:44px auto 0; background:{PURPLE}; color:#fff; font-weight:800; font-size:46px; letter-spacing:1px; padding:20px 40px; border-radius:999px; opacity:0">Order early</span>
        <span id="{cid}-addr" style="display:block; margin-top:40px; color:{INK}; font-weight:800; font-size:46px; letter-spacing:-1px; opacity:0">322 N H St · (805) 736-2700</span>
        <span id="{cid}-pres" style="display:block; margin-top:30px; color:rgba(36,22,41,0.58); font-weight:700; font-size:26px; letter-spacing:4px; text-transform:uppercase; opacity:0">A Lompoc Locals member</span>
      </div>'''
        js = (f'tl.fromTo("#{cid}-logo", {{ autoAlpha:0, y:18, scale:0.97 }}, {{ autoAlpha:1, y:0, scale:1, duration:0.5, ease:"expo.out" }}, 0.15);'
              f'tl.fromTo("#{cid}-cta", {{ autoAlpha:0, scale:0.94 }}, {{ autoAlpha:1, scale:1, duration:0.42, ease:"back.out(1.5)" }}, 0.90);'
              f'tl.fromTo("#{cid}-addr", {{ autoAlpha:0, y:12 }}, {{ autoAlpha:1, y:0, duration:0.4 }}, 1.55);'
              f'tl.fromTo("#{cid}-pres", {{ autoAlpha:0 }}, {{ autoAlpha:1, duration:0.4 }}, 2.60);')
        return wrap(cid, dur, inner, js, bug=False)
    raise ValueError(cid)

def subs_scene():
    cid = "subs"
    items = "".join(f'\n      <div class="sub" id="sub-{i}"><span>{t}</span></div>' for i, (_, _, t) in enumerate(SUBS))
    js = ",\n          ".join(f"[{a:.2f}, {b:.2f}]" for a, b, _ in SUBS)
    return f'''<template>
  <div data-composition-id="{cid}" data-width="1080" data-height="1920" data-duration="{TOTAL:.2f}" style="position:absolute; inset:0; overflow:hidden; background:transparent; pointer-events:none">
    <style>
      [data-composition-id="{cid}"] .wrapz {{ position:absolute; left:60px; right:60px; bottom:310px; z-index:70; display:flex; justify-content:center; }}
      [data-composition-id="{cid}"] .sub {{ position:absolute; left:0; right:0; bottom:0; display:flex; justify-content:center; opacity:0; }}
      [data-composition-id="{cid}"] .sub span {{ display:inline-block; max-width:920px; background:rgba(0,0,0,0.62); color:#fff; font-weight:600; font-size:40px; line-height:1.28; padding:13px 26px; border-radius:18px; text-align:center; }}
    </style>
    <div class="wrapz" data-layout-allow-overlap>{items}
    </div>
    <script>
      (() => {{
        const S = [
          {js}
        ];
        const tl = gsap.timeline({{ paused:true }});
        S.forEach(([a,b], i) => {{
          tl.fromTo("#sub-"+i, {{ autoAlpha:0, y:8 }}, {{ autoAlpha:1, y:0, duration:0.13 }}, a);
          tl.to("#sub-"+i, {{ autoAlpha:0, duration:0.11 }}, b-0.11);
        }});
        tl.set({{}}, {{}}, {TOTAL:.2f});
        window.__timelines["{cid}"] = tl;
      }})();
    </script>
  </div>
</template>
'''

def index_html():
    rows = [f'      <div id="el-{c}" data-composition-id="{c}" data-composition-src="compositions/{c}.html" data-start="{s:.2f}" data-duration="{d:.2f}" data-track-index="{i+1}"></div>' for i,(c,s,d) in enumerate(SCENES)]
    n = len(SCENES)
    rows.append(f'      <div id="el-subs" data-composition-id="subs" data-composition-src="compositions/subs.html" data-start="0" data-duration="{TOTAL:.2f}" data-track-index="{n+1}"></div>')
    a0 = n + 2
    auto = '{"version": 1, "lanes": [{"target": "volume", "points": [{"t": 0, "v": 0}, {"t": 0.5, "v": 0.25}, {"t": %.2f, "v": 0.25}, {"t": %.2f, "v": 0}]}]}' % (TOTAL-1.4, TOTAL)
    return f'''<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1080, height=1920" />
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>
    <style>
      * {{ margin:0; padding:0; box-sizing:border-box; }}
      @font-face {{ font-family:"Plus Jakarta Sans"; src:url("public/fonts/plus-jakarta-sans-latin.woff2") format("woff2"); font-weight:200 800; font-style:normal; }}
      html, body {{ margin:0; width:1080px; height:1920px; overflow:hidden; background:{BG}; }}
      body {{ font-family:"Plus Jakarta Sans", sans-serif; }}
      #root {{ position:relative; width:1080px; height:1920px; overflow:hidden; }}
      #root > div[data-composition-src] {{ position:absolute; inset:0; }}
    </style>
  </head>
  <body>
    <!-- LOMPOC VALLEY FLORIST — Homecoming corsages. Client's own photos (their IG carousel, cropped
         off their baked-in text). Dates as they announced: Cabrillo Sat Oct 3, Lompoc Sat Oct 24. -->
    <div id="root" data-composition-id="main" data-start="0" data-duration="{TOTAL:.2f}" data-width="1080" data-height="1920">
{chr(10).join(rows)}

      <audio id="vo" class="clip" data-audio-group="voiceover" src="public/vo.wav" data-start="{VO_START:.2f}" data-media-start="0" data-duration="{VO_DUR:.2f}" data-track-index="{a0}" data-volume="0.78" data-fade-in="0.05" data-fade-out="0.12"></audio>
      <audio id="music-bed" class="clip" data-audio-group="music" src="public/bed.wav" data-start="0" data-media-start="0" data-duration="{TOTAL:.2f}" data-track-index="{a0+1}" data-volume="0.25" data-fade-in="0.5" data-fade-out="1.4" data-automation='{auto}' data-fx-carve='{{"enabled":true,"sources":["voiceover"],"strength":0.55}}'></audio>
      <audio id="sfx-1" class="clip" data-audio-group="sfx" src="public/whoosh.wav" data-start="2.40" data-media-start="0" data-duration="1.10" data-track-index="{a0+2}" data-volume="0.16" data-fade-out="0.3"></audio>
      <audio id="sfx-2" class="clip" data-audio-group="sfx" src="public/whoosh.wav" data-start="12.00" data-media-start="0" data-duration="1.10" data-track-index="{a0+2}" data-volume="0.18" data-fade-out="0.3"></audio>
    </div>
    <script>window.__timelines["main"] = gsap.timeline({{ paused:true }});</script>
  </body>
</html>
'''

os.makedirs(os.path.join(HERE, "compositions"), exist_ok=True)
for c, s, d in SCENES:
    open(os.path.join(HERE, f"compositions/{c}.html"), "w").write(scene_html(c, d))
open(os.path.join(HERE, "compositions/subs.html"), "w").write(subs_scene())
open(os.path.join(HERE, "index.html"), "w").write(index_html())
print("wrote", [s[0] for s in SCENES])
