// Static hotel data for Lompoc, CA.
// This will be replaced by CMO-curated DB content once KRE-262 is complete.

export type Hotel = {
  slug: string
  name: string
  category: "budget" | "mid-range" | "boutique"
  tagline: string
  description: string
  address: string
  avenue?: string // Street/avenue context for tourists
  neighborhood?: string // Area description
  phone: string
  website: string | null
  amenities: string[]
  priceRange: "$" | "$$" | "$$$"
  rating: number // out of 5
  coverUrl: string | null
  lat: number
  lng: number
}

export const HOTELS: Hotel[] = [
  // ── Upscale / $$$
  {
    slug: "embassy-suites-lompoc",
    name: "Embassy Suites by Hilton Lompoc",
    category: "boutique",
    tagline: "All-suite stays with complimentary reception",
    description:
      "Hilton's all-suite Embassy brand in Lompoc. Every room is a two-room suite, and guests enjoy the complimentary evening reception with drinks and snacks — perfect after a day of wine tasting in the Santa Rita Hills.",
    address: "1117 N H St, Lompoc, CA 93436",
    avenue: "N H Street (Hotel Corridor)",
    neighborhood: "North Lompoc — near major dining and shopping",
    phone: "(805) 735-8500",
    website: "https://www.hilton.com/en/hotels/lmpcaes-embassy-suites-lompoc/",
    amenities: ["Free Wi-Fi", "Free Breakfast", "Evening Reception", "Indoor Pool", "Fitness Center", "Free Parking"],
    priceRange: "$$$",
    rating: 4.2,
    coverUrl: null,
    lat: 34.6475,
    lng: -120.453,
  },
  {
    slug: "hilton-garden-inn-lompoc",
    name: "Hilton Garden Inn Lompoc",
    category: "mid-range",
    tagline: "Modern comfort in the heart of Lompoc",
    description:
      "A contemporary Hilton Garden Inn with an on-site restaurant, outdoor pool, and well-appointed rooms. Ideal for business travelers visiting Vandenberg Space Force Base and leisure guests exploring the Central Coast wine region.",
    address: "1101 N H St, Lompoc, CA 93436",
    avenue: "N H Street (Hotel Corridor)",
    neighborhood: "North Lompoc — walkable to restaurants and shops",
    phone: "(805) 735-8700",
    website: "https://www.hilton.com/en/hotels/lmpcagi-hilton-garden-inn-lompoc/",
    amenities: ["Free Wi-Fi", "On-Site Restaurant", "Outdoor Pool", "Fitness Center", "Free Parking", "24-hr Front Desk"],
    priceRange: "$$$",
    rating: 4.0,
    coverUrl: null,
    lat: 34.648,
    lng: -120.4525,
  },
  {
    slug: "quality-inn-lompoc",
    name: "Quality Inn Lompoc",
    category: "budget",
    tagline: "Comfortable stays at honest prices",
    description:
      "A reliable, well-maintained hotel conveniently located on N H Street near dining, shopping, and the heart of Lompoc. Great for travelers visiting Vandenberg Space Force Base or exploring the Central Coast wine country.",
    address: "1621 N H St, Lompoc, CA 93436",
    avenue: "N H Street (Hotel Corridor)",
    neighborhood: "North Lompoc — 5 min to downtown, 10 min to Vandenberg Gate",
    phone: "(805) 735-8555",
    website: "https://www.choicehotels.com",
    amenities: ["Free Wi-Fi", "Free Parking", "Outdoor Pool", "Pet-Friendly", "Continental Breakfast"],
    priceRange: "$",
    rating: 3.5,
    coverUrl: null,
    lat: 34.6511,
    lng: -120.4578,
  },
  {
    slug: "holiday-inn-express-lompoc",
    name: "Holiday Inn Express & Suites Lompoc",
    category: "mid-range",
    tagline: "Smart stays in the Flower Capital",
    description:
      "Modern comfort in the heart of Lompoc. Spacious rooms, a complimentary hot breakfast, and easy access to wine tasting rooms and the historic downtown make this a top pick for families and business travelers alike.",
    address: "1417 N H St, Lompoc, CA 93436",
    avenue: "N H Street (Hotel Corridor)",
    neighborhood: "North Lompoc — walkable to restaurants, 3 blocks from Ocean Ave",
    phone: "(805) 735-8720",
    website: "https://www.ihg.com",
    amenities: ["Free Wi-Fi", "Hot Breakfast", "Indoor Pool", "Fitness Center", "Business Center", "Free Parking"],
    priceRange: "$$",
    rating: 4.0,
    coverUrl: null,
    lat: 34.6490,
    lng: -120.4578,
  },
  {
    slug: "hampton-inn-lompoc",
    name: "Hampton Inn & Suites Lompoc",
    category: "mid-range",
    tagline: "Hampton's 100% satisfaction guarantee",
    description:
      "Hilton's trusted Hampton brand brings clean, consistent hospitality to Lompoc. Whether you're here for the Santa Rita Hills wine trail, a Vandenberg visit, or the annual Flower Festival, Hampton delivers the reliability you expect.",
    address: "1201 N H St, Lompoc, CA 93436",
    avenue: "N H Street (Hotel Corridor)",
    neighborhood: "Central Lompoc — minutes from Ocean Avenue and downtown shops",
    phone: "(805) 735-0777",
    website: "https://www.hilton.com",
    amenities: ["Free Wi-Fi", "Hot Breakfast", "Pool", "Fitness Center", "Free Parking", "24-hr Front Desk"],
    priceRange: "$$",
    rating: 4.2,
    coverUrl: null,
    lat: 34.6463,
    lng: -120.4578,
  },
  {
    slug: "cabrillo-inn-lompoc",
    name: "Cabrillo Inn",
    category: "budget",
    tagline: "Local roots, friendly rates",
    description:
      "A locally owned motel offering simple, affordable accommodations. Centrally located and steps from Ocean Avenue, the Cabrillo Inn is a no-fuss option for budget-conscious travelers who want to be close to Lompoc's local dining and shops.",
    address: "1107 E Ocean Ave, Lompoc, CA 93436",
    avenue: "E Ocean Avenue",
    neighborhood: "Central Lompoc — on the main commercial boulevard",
    phone: "(805) 735-6777",
    website: null,
    amenities: ["Free Wi-Fi", "Free Parking", "Pet-Friendly", "Microwave & Fridge in rooms"],
    priceRange: "$",
    rating: 3.2,
    coverUrl: null,
    lat: 34.6393,
    lng: -120.4513,
  },
  {
    slug: "days-inn-lompoc",
    name: "Days Inn by Wyndham Lompoc",
    category: "budget",
    tagline: "Simple comfort, great value",
    description:
      "A no-frills Wyndham-branded property on the N H Street hotel strip. Clean rooms and easy freeway access make this a solid base for short stays near Vandenberg Space Force Base or the Santa Rita Hills wine region.",
    address: "1415 N H St, Lompoc, CA 93436",
    avenue: "N H Street (Hotel Corridor)",
    neighborhood: "North Lompoc — across from Holiday Inn Express",
    phone: "(805) 736-0707",
    website: "https://www.wyndhamhotels.com",
    amenities: ["Free Wi-Fi", "Free Parking", "Outdoor Pool", "Pet-Friendly"],
    priceRange: "$",
    rating: 3.0,
    coverUrl: null,
    lat: 34.6488,
    lng: -120.4580,
  },
  {
    slug: "surestay-best-western-lompoc",
    name: "SureStay Hotel by Best Western Lompoc",
    category: "budget",
    tagline: "Dependable stays, Best Western quality",
    description:
      "Part of the Best Western family, SureStay offers clean, affordable rooms on the northern stretch of H Street. Conveniently close to fast food, gas stations, and the main road to Vandenberg, it's a practical stop for base visitors and road-trippers.",
    address: "1616 N H St, Lompoc, CA 93436",
    avenue: "N H Street (Hotel Corridor)",
    neighborhood: "North Lompoc — near the Hwy 1 junction",
    phone: "(805) 735-7744",
    website: "https://www.bestwestern.com",
    amenities: ["Free Wi-Fi", "Free Parking", "Continental Breakfast", "24-hr Front Desk"],
    priceRange: "$",
    rating: 3.3,
    coverUrl: null,
    lat: 34.6508,
    lng: -120.4579,
  },
  {
    slug: "civic-center-motel-lompoc",
    name: "Civic Center Motel",
    category: "budget",
    tagline: "Downtown proximity at motel prices",
    description:
      "An independently owned motel steps from Lompoc's civic center and Ocean Avenue. Basic amenities at affordable prices — ideal for solo travelers, contractors, and visitors who just need a clean room close to city hall and local eateries.",
    address: "918 E Ocean Ave, Lompoc, CA 93436",
    avenue: "E Ocean Avenue",
    neighborhood: "Downtown Lompoc — adjacent to Civic Center and La Purísima Mission corridor",
    phone: "(805) 735-2272",
    website: null,
    amenities: ["Free Wi-Fi", "Free Parking", "Microwave & Fridge in rooms"],
    priceRange: "$",
    rating: 2.9,
    coverUrl: null,
    lat: 34.6391,
    lng: -120.4529,
  },
  {
    slug: "ocairns-inn-lompoc",
    name: "O'Cairns Inn & Suites",
    category: "mid-range",
    tagline: "Charming local inn with a garden courtyard",
    description:
      "A beloved locally owned inn in central Lompoc featuring a peaceful garden courtyard. Personalized service sets O'Cairns apart — a great base for exploring Old Town murals, the Wine Ghetto, and nearby flower fields.",
    address: "1888 N H St, Lompoc, CA 93436",
    avenue: "N H Street (Hotel Corridor)",
    neighborhood: "North Lompoc — near the wine ghetto district",
    phone: "(805) 735-8601",
    website: null,
    amenities: ["Free Wi-Fi", "Free Parking", "Garden Courtyard", "Continental Breakfast"],
    priceRange: "$$",
    rating: 3.7,
    coverUrl: null,
    lat: 34.641,
    lng: -120.456,
  },
  {
    slug: "inn-of-lompoc",
    name: "Inn of Lompoc",
    category: "budget",
    tagline: "Budget-friendly stays with outdoor pool",
    description:
      "A classic roadside inn offering clean, affordable accommodations with an outdoor pool. Conveniently located with easy highway access — a practical choice for travelers passing through or staying near Vandenberg.",
    address: "1021 E Ocean Ave, Lompoc, CA 93436",
    avenue: "E Ocean Avenue",
    neighborhood: "Central Lompoc — on the main commercial boulevard",
    phone: "(805) 735-7744",
    website: null,
    amenities: ["Free Wi-Fi", "Free Parking", "Outdoor Pool", "Pet-Friendly"],
    priceRange: "$",
    rating: 3.3,
    coverUrl: null,
    lat: 34.636,
    lng: -120.459,
  },
  {
    slug: "lotus-of-lompoc",
    name: "Lotus of Lompoc",
    category: "boutique",
    tagline: "Cozy boutique feel with personalized service",
    description:
      "A small, independently operated inn with a boutique atmosphere. The Lotus of Lompoc offers personalized, attentive service that chain hotels can't match — ideal for couples and solo travelers who want a more intimate stay.",
    address: "1415 E Ocean Ave, Lompoc, CA 93436",
    avenue: "E Ocean Avenue",
    neighborhood: "Central Lompoc — near local cafés and galleries",
    phone: "(805) 735-0101",
    website: null,
    amenities: ["Free Wi-Fi", "Free Parking", "Microwave & Fridge in rooms"],
    priceRange: "$",
    rating: 3.5,
    coverUrl: null,
    lat: 34.6395,
    lng: -120.4545,
  },
  {
    slug: "village-inn-lompoc",
    name: "Village Inn",
    category: "budget",
    tagline: "Classic inn steps from Old Town",
    description:
      "A simple, affordable inn within walking distance of Lompoc's Old Town with its murals, Friday Market, and local eateries. The Village Inn is the closest budget option to the historic downtown core.",
    address: "888 N H St, Lompoc, CA 93436",
    avenue: "N H Street (Hotel Corridor)",
    neighborhood: "Central Lompoc — walking distance to Old Town and civic center",
    phone: "(805) 736-0500",
    website: null,
    amenities: ["Free Wi-Fi", "Free Parking"],
    priceRange: "$",
    rating: 3.2,
    coverUrl: null,
    lat: 34.637,
    lng: -120.458,
  },
  {
    slug: "motel-6-lompoc",
    name: "Motel 6 Lompoc",
    category: "budget",
    tagline: "Affordable, pet-friendly — we'll leave the light on",
    description:
      "America's most recognized budget chain. Motel 6 Lompoc is clean, reliable, and welcoming to pets. Free parking and easy freeway access make it the go-to for road-trippers and budget-conscious travelers.",
    address: "1521 N H St, Lompoc, CA 93436",
    avenue: "N H Street (Hotel Corridor)",
    neighborhood: "North Lompoc — near freeway on-ramp",
    phone: "(805) 735-7631",
    website: "https://www.motel6.com",
    amenities: ["Free Wi-Fi", "Free Parking", "Pet-Friendly", "Outdoor Pool"],
    priceRange: "$",
    rating: 3.0,
    coverUrl: null,
    lat: 34.634,
    lng: -120.46,
  },
  {
    slug: "red-roof-inn-lompoc",
    name: "Red Roof Inn Lompoc",
    category: "budget",
    tagline: "No-frills comfort, free parking, pet-friendly",
    description:
      "Red Roof Inn delivers dependable, budget-friendly stays with free parking and a pet-friendly policy. A solid base for Vandenberg visitors and anyone needing straightforward accommodations without surprise fees.",
    address: "1411 N H St, Lompoc, CA 93436",
    avenue: "N H Street (Hotel Corridor)",
    neighborhood: "North Lompoc — adjacent to major chain restaurants",
    phone: "(805) 735-0800",
    website: "https://www.redroof.com",
    amenities: ["Free Wi-Fi", "Free Parking", "Pet-Friendly", "24-hr Front Desk"],
    priceRange: "$",
    rating: 3.0,
    coverUrl: null,
    lat: 34.633,
    lng: -120.4615,
  },
]

export function getHotelBySlug(slug: string): Hotel | undefined {
  return HOTELS.find((h) => h.slug === slug)
}
