import type { CategoryId } from "./map-categories"

export interface POI {
  id: string
  name: string
  lat: number
  lng: number
  category: CategoryId
  highlight: string
  rating?: number
  price?: string
  type?: string
}

export const POIS: POI[] = [
  // Hotels & Stays
  {
    id: "embassy-suites",
    name: "Embassy Suites by Hilton Lompoc",
    lat: 34.6475,
    lng: -120.453,
    category: "hotels",
    highlight: "Full suites, complimentary breakfast & evening reception",
    rating: 4.2,
    price: "$$$",
  },
  {
    id: "hilton-garden-inn",
    name: "Hilton Garden Inn Lompoc",
    lat: 34.648,
    lng: -120.4525,
    category: "hotels",
    highlight: "Modern rooms, on-site restaurant, pool",
    rating: 4.0,
    price: "$$$",
  },
  {
    id: "holiday-inn-express",
    name: "Holiday Inn Express Lompoc",
    lat: 34.635,
    lng: -120.461,
    category: "hotels",
    highlight: "Free breakfast, indoor pool, reliable comfort",
    rating: 3.8,
    price: "$$",
  },
  {
    id: "surestay-best-western",
    name: "SureStay Plus by Best Western",
    lat: 34.6385,
    lng: -120.457,
    category: "hotels",
    highlight: "Free Wi-Fi, parking, continental breakfast",
    rating: 3.6,
    price: "$$",
  },
  {
    id: "ocairns-inn",
    name: "O'Cairns Inn & Suites",
    lat: 34.641,
    lng: -120.456,
    category: "hotels",
    highlight: "Charming local inn with garden courtyard",
    rating: 3.7,
    price: "$$",
  },
  {
    id: "inn-of-lompoc",
    name: "Inn of Lompoc",
    lat: 34.636,
    lng: -120.459,
    category: "hotels",
    highlight: "Budget-friendly, outdoor pool, highway access",
    rating: 3.3,
    price: "$",
  },
  {
    id: "lotus-of-lompoc",
    name: "Lotus of Lompoc",
    lat: 34.6395,
    lng: -120.4545,
    category: "hotels",
    highlight: "Cozy boutique feel, personalized service",
    rating: 3.5,
    price: "$",
  },
  {
    id: "village-inn",
    name: "Village Inn",
    lat: 34.637,
    lng: -120.458,
    category: "hotels",
    highlight: "Classic inn, walking distance to Old Town",
    rating: 3.2,
    price: "$",
  },
  {
    id: "motel-6",
    name: "Motel 6 Lompoc",
    lat: 34.634,
    lng: -120.46,
    category: "hotels",
    highlight: "Affordable, pet-friendly",
    rating: 3.0,
    price: "$",
  },
  {
    id: "red-roof-inn",
    name: "Red Roof Inn Lompoc",
    lat: 34.633,
    lng: -120.4615,
    category: "hotels",
    highlight: "No-frills, free parking, pet-friendly",
    rating: 3.0,
    price: "$",
  },

  // Wine & Dining
  {
    id: "wine-ghetto",
    name: "Lompoc Wine Ghetto",
    lat: 34.642,
    lng: -120.4498,
    category: "wine",
    highlight: "17+ tasting rooms in one industrial complex — the crown jewel",
    type: "Wine District",
  },
  {
    id: "palmina-wines",
    name: "Palmina Wines",
    lat: 34.6418,
    lng: -120.4502,
    category: "wine",
    highlight: "Italian varietals from Santa Barbara County",
    type: "Tasting Room",
  },
  {
    id: "fiddlehead-cellars",
    name: "Fiddlehead Cellars",
    lat: 34.6422,
    lng: -120.4495,
    category: "wine",
    highlight: "Award-winning Pinot Noir and Sauvignon Blanc",
    type: "Tasting Room",
  },
  {
    id: "flying-goat-cellars",
    name: "Flying Goat Cellars",
    lat: 34.6425,
    lng: -120.4492,
    category: "wine",
    highlight: "Small-batch Pinot Noir specialist",
    type: "Tasting Room",
  },
  {
    id: "craft-beer-trail",
    name: "Lompoc Craft Beer Trail",
    lat: 34.639,
    lng: -120.4565,
    category: "wine",
    highlight: "Local craft breweries worth exploring",
    type: "Brewery Hub",
  },
  {
    id: "south-side-coffee",
    name: "South Side Coffee Co.",
    lat: 34.6388,
    lng: -120.4572,
    category: "wine",
    highlight: "Best local coffee and pastries",
    type: "Café",
  },
  {
    id: "sissys-uptown",
    name: "Sissy's Uptown Café",
    lat: 34.6392,
    lng: -120.4568,
    category: "wine",
    highlight: "Beloved local brunch spot",
    type: "Restaurant",
  },

  // History & Culture
  {
    id: "la-purisima-mission",
    name: "La Purisima Mission State Historic Park",
    lat: 34.6689,
    lng: -120.419,
    category: "history",
    highlight: "Most fully restored of California's 21 missions. Daily tours at 1 PM",
  },
  {
    id: "lompoc-museum",
    name: "Lompoc Museum",
    lat: 34.6388,
    lng: -120.4578,
    category: "history",
    highlight: "Local history from Chumash to present day",
  },
  {
    id: "mural-walk",
    name: "Old Town Mural Walk",
    lat: 34.6385,
    lng: -120.4575,
    category: "history",
    highlight: "Self-guided tour of 30+ stunning outdoor murals",
  },
  {
    id: "cypress-gallery",
    name: "Cypress Gallery",
    lat: 34.639,
    lng: -120.458,
    category: "history",
    highlight: "Rotating exhibits from local artists",
  },

  // Outdoor & Beach
  {
    id: "jalama-beach",
    name: "Jalama Beach County Park",
    lat: 34.5108,
    lng: -120.5004,
    category: "outdoor",
    highlight: "Hidden gem beach — camping, surfing, and the famous Jalama Burger",
  },
  {
    id: "surf-beach",
    name: "Surf Beach",
    lat: 34.685,
    lng: -120.605,
    category: "outdoor",
    highlight: "Popular surf spot near Vandenberg",
  },
  {
    id: "river-park-trail",
    name: "River Park Trail",
    lat: 34.64,
    lng: -120.465,
    category: "outdoor",
    highlight: "Scenic walking and biking along the Santa Ynez River",
  },
  {
    id: "allan-hancock-trail",
    name: "Allan Hancock Trail",
    lat: 34.645,
    lng: -120.47,
    category: "outdoor",
    highlight: "Easy hiking with valley views",
  },
  {
    id: "skydive-lompoc",
    name: "Skydive Lompoc",
    lat: 34.665,
    lng: -120.468,
    category: "outdoor",
    highlight: "Tandem jumps with views of the Channel Islands",
  },

  // Flowers & Nature
  {
    id: "flower-fields",
    name: "Lompoc Flower Fields",
    lat: 34.65,
    lng: -120.44,
    category: "flowers",
    highlight: "Sweet pea, larkspur & more — blooming April through September",
  },
  {
    id: "vandenberg-launches",
    name: "Vandenberg Launch Viewing",
    lat: 34.7483,
    lng: -120.5182,
    category: "flowers",
    highlight: "Watch rocket launches from public viewing areas",
  },

  // Events & Fun
  {
    id: "flower-festival",
    name: "Lompoc Flower Festival (Ryon Park)",
    lat: 34.638,
    lng: -120.462,
    category: "events",
    highlight: "Annual celebration of Lompoc's floral heritage",
  },
  {
    id: "friday-market",
    name: "Old Town Friday Market",
    lat: 34.6387,
    lng: -120.4573,
    category: "events",
    highlight: "Weekly farmers market — produce, crafts, live music",
  },
]
