#!/usr/bin/env python3
"""LAUNCH ALERT — Falcon 9 / Starlink Group 15-27, SLC-4E Vandenberg, Sat Sep 19 2026, 6:47 PM PT.
Facts from our own launch-library feed (event 193, starts_at 2026-09-20T01:47Z).
Imagery: U.S. Space Force photo of a Falcon 9 night launch from SLC-4E — public domain
(17 U.S.C. §105), provenance in content/social/assets/LAUNCH-PHOTO-CREDIT.md.
15.6 s, 9:16. Generated by: python3 gen.py
"""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
X = 0.30
SCENES = [("s1-alert", 0.00, 4.20), ("s2-what", 4.00, 4.20), ("s3-where", 8.00, 3.40), ("s4-end", 11.20, 4.40)]
TOTAL = 15.60
VO_START = 0.55; VO_DUR = 13.60
SUBS = [
    (0.55, 2.10,  "Heads up, Lompoc."),
    (2.35, 5.90,  "Tonight at 6:47, a Falcon 9 lifts off from Vandenberg."),
    (6.20, 8.05,  "27 Starlink satellites."),
    (8.35, 9.70,  "Look southwest."),
    (10.10, 13.90, "Launch times shift, so check before you step outside."),
]
GOLD = "#efc618"; EMBER = "#ff9a3c"; INK = "#0a0805"; PURPLE = "#650c75"; CREAM = "#fdf6e9"

def css(cid):
    return f"""
      [data-composition-id="{cid}"] .stage {{ position:absolute; inset:0; opacity:0; will-change:opacity; }}
      [data-composition-id="{cid}"] .wrap {{ position:absolute; inset:0; overflow:hidden; will-change:transform; transform-origin:50% 50%; }}
      [data-composition-id="{cid}"] .cover {{ position:absolute; inset:0; width:100%; height:100%; object-fit:cover; display:block; }}
      [data-composition-id="{cid}"] .heat {{ position:absolute; inset:0; z-index:29; pointer-events:none;
          background: radial-gradient(38% 30% at 50% 44%, rgba(255,154,60,0.26) 0%, rgba(255,154,60,0) 68%); }}
      [data-composition-id="{cid}"] .vig {{ position:absolute; inset:0; z-index:30; pointer-events:none;
          background: radial-gradient(ellipse 96% 78% at 50% 44%, rgba(6,4,3,0) 46%, rgba(6,4,3,0.82) 100%); }}
      [data-composition-id="{cid}"] .scrim {{ position:absolute; inset:0; z-index:31; pointer-events:none;
          background: linear-gradient(to top, rgba(6,4,3,0.96) 0%, rgba(6,4,3,0.62) 32%, rgba(6,4,3,0.06) 62%); }}
      [data-composition-id="{cid}"] .topscrim {{ position:absolute; inset:0; z-index:31; pointer-events:none;
          background: linear-gradient(to bottom, rgba(6,4,3,0.82) 0%, rgba(6,4,3,0.28) 22%, rgba(6,4,3,0) 40%); }}
      [data-composition-id="{cid}"] .grain {{ position:absolute; inset:0; pointer-events:none; opacity:0.09; z-index:50;
          background-image:url("data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 width=%27200%27 height=%27200%27%3E%3Cfilter id=%27n%27%3E%3CfeTurbulence type=%27fractalNoise%27 baseFrequency=%270.9%27 numOctaves=%272%27/%3E%3C/filter%3E%3Crect width=%27200%27 height=%27200%27 filter=%27url(%23n)%27 opacity=%271%27/%3E%3C/svg%3E"); }}
      [data-composition-id="{cid}"] .mark {{ position:absolute; top:150px; right:84px; width:84px; height:auto; z-index:45; opacity:0.9; }}
      [data-composition-id="{cid}"] .alert {{ position:absolute; left:84px; top:150px; z-index:45; display:flex; align-items:center; }}
      [data-composition-id="{cid}"] .alert .dot {{ width:20px; height:20px; border-radius:50%; background:{EMBER}; margin-right:16px; box-shadow:0 0 22px rgba(255,154,60,0.95); }}
      [data-composition-id="{cid}"] .alert .txt {{ color:{GOLD}; font-weight:800; font-size:30px; letter-spacing:7px; text-transform:uppercase; }}
      [data-composition-id="{cid}"] .hero {{ color:#fff; font-weight:800; line-height:0.94; letter-spacing:-5px; text-shadow:0 10px 44px rgba(6,4,3,0.9); }}
      [data-composition-id="{cid}"] .facts {{ position:absolute; left:84px; right:84px; bottom:430px; z-index:40; }}
      [data-composition-id="{cid}"] .fact {{ display:flex; align-items:center; opacity:0; will-change:transform,opacity; }}
      [data-composition-id="{cid}"] .fact .bar {{ width:6px; height:52px; background:{GOLD}; border-radius:3px; margin-right:24px; }}
      [data-composition-id="{cid}"] .fact .t {{ color:{CREAM}; font-weight:800; font-size:52px; letter-spacing:-1.5px; }}
    """

def wrap(cid, dur, inner, js, first=False, alert=True):
    fade = (f'tl.set("#{cid}-stage", {{ autoAlpha:1 }}, 0);' if first
            else f'tl.fromTo("#{cid}-stage", {{ autoAlpha:0 }}, {{ autoAlpha:1, duration:{X}, ease:"power1.inOut" }}, 0);')
    a = (f'<div class="alert" id="{cid}-alert"><span class="dot" id="{cid}-dot"></span>'
         f'<span class="txt">Launch alert</span></div>') if alert else ""
    ajs = (f'tl.to("#{cid}-dot", {{ opacity:0.25, duration:0.5, ease:"sine.inOut", yoyo:true, repeat:{int(dur/0.5)} }}, 0);') if alert else ""
    return f'''<template>
  <div data-composition-id="{cid}" data-width="1080" data-height="1920" data-duration="{dur:.2f}" style="position:absolute; inset:0; overflow:hidden; background:{INK if first else 'transparent'}">
    <style>{css(cid)}
    </style>
    <div class="stage" id="{cid}-stage"{' style="opacity:1"' if first else ''}>
      {inner}
      <div class="heat"></div><div class="vig"></div>
    </div>
    {a}
    <img class="mark" src="public/mark-white.png" alt="" />
    <div class="grain"></div>
    <script>
      (() => {{
        const tl = gsap.timeline({{ paused:true, defaults:{{ ease:"power3.out", duration:0.5 }} }});
        {fade}{ajs}
        {js}
        tl.set({{}}, {{}}, {dur:.2f});
        window.__timelines["{cid}"] = tl;
      }})();
    </script>
  </div>
</template>
'''

def scene_html(cid, dur):
    if cid == "s1-alert":
        inner = f'''<div class="wrap" id="{cid}-w" data-layout-allow-overflow><img class="cover" src="public/hero.jpg" alt="" style="object-position:50% 42%" /></div>
      <div class="scrim"></div><div class="topscrim"></div>
      <div style="position:absolute; left:84px; right:84px; bottom:26%; z-index:40">
        <span id="{cid}-k" style="display:block; color:{GOLD}; font-weight:800; font-size:32px; letter-spacing:7px; text-transform:uppercase; opacity:1">Tonight over Vandenberg</span>
        <span class="hero" id="{cid}-t" style="display:block; margin-top:26px; margin-bottom:18px; font-size:190px; line-height:1.0; opacity:1">6:47</span>
        <span id="{cid}-p" style="display:block; color:rgba(253,246,233,0.88); font-weight:700; font-size:46px; letter-spacing:2px; opacity:1">PM &nbsp;·&nbsp; Saturday</span>
      </div>'''
        js = (f'tl.fromTo("#{cid}-w", {{ scale:1.0 }}, {{ scale:1.10, duration:{dur:.2f}, ease:"none" }}, 0);'
              f'tl.fromTo("#{cid}-t", {{ scale:1.05 }}, {{ scale:1, duration:1.6, ease:"expo.out" }}, 0.05);')
        return wrap(cid, dur, inner, js, first=True)
    if cid == "s2-what":
        rows = [("Falcon 9", 0.35), ("27 Starlink satellites", 1.35), ("Space Launch Complex 4E", 2.35)]
        facts = "".join(
            f'<div class="fact" id="{cid}-f{i}" style="margin-bottom:26px"><span class="bar"></span><span class="t">{t}</span></div>'
            for i, (t, _) in enumerate(rows))
        inner = f'''<div class="wrap" id="{cid}-w" data-layout-allow-overflow><img class="cover" src="public/plume.jpg" alt="" style="object-position:50% 46%" /></div>
      <div class="scrim"></div><div class="topscrim"></div>
      <div class="facts" style="bottom:400px">{facts}</div>'''
        js = f'tl.fromTo("#{cid}-w", {{ scale:1.12 }}, {{ scale:1.0, duration:{dur:.2f}, ease:"power2.out" }}, 0);'
        js += "".join(f'tl.fromTo("#{cid}-f{i}", {{ autoAlpha:0, x:-30 }}, {{ autoAlpha:1, x:0, duration:0.45, ease:"expo.out" }}, {at:.2f});'
                      for i, (_, at) in enumerate(rows))
        return wrap(cid, dur, inner, js)
    if cid == "s3-where":
        inner = f'''<div class="wrap" id="{cid}-w" data-layout-allow-overflow><img class="cover" src="public/hero.jpg" alt="" style="object-position:50% 38%" /></div>
      <div class="scrim"></div><div class="topscrim"></div>
      <div style="position:absolute; left:84px; right:84px; bottom:28%; z-index:40">
        <span class="hero" id="{cid}-h" style="display:block; font-size:130px; letter-spacing:-4px; opacity:0">LOOK<br />SOUTHWEST</span>
        <span id="{cid}-s" style="display:block; margin-top:22px; color:rgba(253,246,233,0.84); font-weight:600; font-size:38px; opacity:0">A bright plume climbing out of the dark hills.</span>
      </div>'''
        js = (f'tl.fromTo("#{cid}-w", {{ scale:1.06 }}, {{ scale:1.14, duration:{dur:.2f}, ease:"none" }}, 0);'
              f'tl.fromTo("#{cid}-h", {{ autoAlpha:0, y:24 }}, {{ autoAlpha:1, y:0, duration:0.5, ease:"expo.out" }}, 0.15);'
              f'tl.fromTo("#{cid}-s", {{ autoAlpha:0, y:14 }}, {{ autoAlpha:1, y:0, duration:0.42 }}, 0.85);')
        return wrap(cid, dur, inner, js)
    if cid == "s4-end":
        inner = f'''<div style="position:absolute; inset:0; background:linear-gradient(180deg, #16100a 0%, {INK} 55%, #0d0a14 100%)"></div>
      <div style="position:absolute; left:0; right:0; top:29%; z-index:40; text-align:center">
        <span id="{cid}-t1" style="display:block; color:#fff; font-weight:800; font-size:78px; line-height:1.04; letter-spacing:-2px; opacity:0">Launch times<br />shift.</span>
        <span id="{cid}-t2" style="display:block; margin-top:26px; color:rgba(253,246,233,0.82); font-weight:600; font-size:38px; opacity:0">Check before you step outside.</span>
        <span id="{cid}-pill" style="display:block; width:fit-content; margin:46px auto 0; background:{GOLD}; color:{INK}; font-weight:800; font-size:40px; padding:20px 38px; border-radius:999px; opacity:0">lompoclocals.com/find/rocket-launch</span>
      </div>'''
        js = (f'tl.fromTo("#{cid}-t1", {{ autoAlpha:0, y:20 }}, {{ autoAlpha:1, y:0, duration:0.5, ease:"expo.out" }}, 0.15);'
              f'tl.fromTo("#{cid}-t2", {{ autoAlpha:0, y:14 }}, {{ autoAlpha:1, y:0, duration:0.4 }}, 0.85);'
              f'tl.fromTo("#{cid}-pill", {{ autoAlpha:0, scale:0.95 }}, {{ autoAlpha:1, scale:1, duration:0.45, ease:"back.out(1.4)" }}, 1.70);')
        return wrap(cid, dur, inner, js, alert=False)
    raise ValueError(cid)

def subs_scene():
    cid = "subs"
    items = "".join(f'\n      <div class="sub" id="sub-{i}"><span>{t}</span></div>' for i, (_, _, t) in enumerate(SUBS))
    js = ",\n          ".join(f"[{a:.2f}, {b:.2f}]" for a, b, _ in SUBS)
    return f'''<template>
  <div data-composition-id="{cid}" data-width="1080" data-height="1920" data-duration="{TOTAL:.2f}" style="position:absolute; inset:0; overflow:hidden; background:transparent; pointer-events:none">
    <style>
      [data-composition-id="{cid}"] .wrapz {{ position:absolute; left:60px; right:60px; bottom:310px; z-index:70; display:flex; justify-content:center; }}
      [data-composition-id="{cid}"] .sub {{ position:absolute; left:0; right:0; bottom:0; display:flex; justify-content:center; opacity:0; }}
      [data-composition-id="{cid}"] .sub span {{ display:inline-block; max-width:920px; background:rgba(0,0,0,0.66); color:#fff; font-weight:600; font-size:41px; line-height:1.26; padding:13px 26px; border-radius:18px; text-align:center; }}
    </style>
    <div class="wrapz" data-layout-allow-overlap>{items}
    </div>
    <script>
      (() => {{
        const S = [
          {js}
        ];
        const tl = gsap.timeline({{ paused:true }});
        S.forEach(([a,b], i) => {{
          tl.fromTo("#sub-"+i, {{ autoAlpha:0, y:8 }}, {{ autoAlpha:1, y:0, duration:0.13 }}, a);
          tl.to("#sub-"+i, {{ autoAlpha:0, duration:0.11 }}, b-0.11);
        }});
        tl.set({{}}, {{}}, {TOTAL:.2f});
        window.__timelines["{cid}"] = tl;
      }})();
    </script>
  </div>
</template>
'''

def progress_scene():
    cid = "progress"
    return f'''<template>
  <div data-composition-id="{cid}" data-width="1080" data-height="1920" data-duration="{TOTAL:.2f}" style="position:absolute; inset:0; overflow:hidden; background:transparent; pointer-events:none">
    <style>[data-composition-id="{cid}"] .bar {{ position:absolute; left:0; right:0; bottom:0; height:8px; background:{EMBER}; transform-origin:0% 50%; z-index:70; box-shadow:0 0 14px rgba(255,154,60,0.7); }}</style>
    <div class="bar" id="prog-bar"></div>
    <script>(() => {{ const tl=gsap.timeline({{paused:true}}); tl.fromTo("#prog-bar",{{scaleX:0}},{{scaleX:1,duration:{TOTAL:.2f},ease:"none"}},0); window.__timelines["{cid}"]=tl; }})();</script>
  </div>
</template>
'''

def index_html():
    has_audio = os.path.exists(os.path.join(HERE, "public", "bed.wav"))
    rows = [f'      <div id="el-{c}" data-composition-id="{c}" data-composition-src="compositions/{c}.html" data-start="{s:.2f}" data-duration="{d:.2f}" data-track-index="{i+1}"></div>' for i,(c,s,d) in enumerate(SCENES)]
    n = len(SCENES)
    rows.append(f'      <div id="el-subs" data-composition-id="subs" data-composition-src="compositions/subs.html" data-start="0" data-duration="{TOTAL:.2f}" data-track-index="{n+1}"></div>')
    rows.append(f'      <div id="el-progress" data-composition-id="progress" data-composition-src="compositions/progress.html" data-start="0" data-duration="{TOTAL:.2f}" data-track-index="{n+2}"></div>')
    a0 = n + 3
    audio = ""
    if has_audio:
        auto = '{"version": 1, "lanes": [{"target": "volume", "points": [{"t": 0, "v": 0}, {"t": 0.5, "v": 0.26}, {"t": %.2f, "v": 0.26}, {"t": %.2f, "v": 0}]}]}' % (TOTAL-1.3, TOTAL)
        audio = f'''
      <audio id="vo" class="clip" data-audio-group="voiceover" src="public/vo.wav" data-start="{VO_START:.2f}" data-media-start="0" data-duration="{VO_DUR:.2f}" data-track-index="{a0}" data-volume="0.78" data-fade-in="0.05" data-fade-out="0.12"></audio>
      <audio id="music-bed" class="clip" data-audio-group="music" src="public/bed.wav" data-start="0" data-media-start="0" data-duration="{TOTAL:.2f}" data-track-index="{a0+1}" data-volume="0.26" data-fade-in="0.5" data-fade-out="1.3" data-automation='{auto}' data-fx-carve='{{"enabled":true,"sources":["voiceover"],"strength":0.55}}'></audio>
      <audio id="sfx-1" class="clip" data-audio-group="sfx" src="public/whoosh.wav" data-start="4.00" data-media-start="0" data-duration="1.20" data-track-index="{a0+2}" data-volume="0.20" data-fade-out="0.3"></audio>'''
    return f'''<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1080, height=1920" />
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>
    <style>
      * {{ margin:0; padding:0; box-sizing:border-box; }}
      @font-face {{ font-family:"Plus Jakarta Sans"; src:url("public/fonts/plus-jakarta-sans-latin.woff2") format("woff2"); font-weight:200 800; font-style:normal; }}
      html, body {{ margin:0; width:1080px; height:1920px; overflow:hidden; background:{INK}; }}
      body {{ font-family:"Plus Jakarta Sans", sans-serif; }}
      #root {{ position:relative; width:1080px; height:1920px; overflow:hidden; }}
      #root > div[data-composition-src] {{ position:absolute; inset:0; }}
    </style>
  </head>
  <body>
    <!-- LAUNCH ALERT — Falcon 9 / Starlink 15-27, SLC-4E Vandenberg, Sat Sep 19 2026 6:47 PM PT.
         Photo: U.S. Space Force, public domain (see content/social/assets/LAUNCH-PHOTO-CREDIT.md). -->
    <div id="root" data-composition-id="main" data-start="0" data-duration="{TOTAL:.2f}" data-width="1080" data-height="1920">
{chr(10).join(rows)}
{audio}
    </div>
    <script>window.__timelines["main"] = gsap.timeline({{ paused:true }});</script>
  </body>
</html>
'''

os.makedirs(os.path.join(HERE, "compositions"), exist_ok=True)
for c, s, d in SCENES:
    open(os.path.join(HERE, f"compositions/{c}.html"), "w").write(scene_html(c, d))
open(os.path.join(HERE, "compositions/subs.html"), "w").write(subs_scene())
open(os.path.join(HERE, "compositions/progress.html"), "w").write(progress_scene())
open(os.path.join(HERE, "index.html"), "w").write(index_html())
print("wrote", [s[0] for s in SCENES], "audio=" + str(os.path.exists(os.path.join(HERE,"public","bed.wav"))))
