import { NextIntlClientProvider } from "next-intl"
import { getMessages, getTranslations } from "next-intl/server"
import type { Metadata } from "next"
import { Toaster } from "@/components/ui/sonner"
import { SiteHeader } from "@/components/site-header"
import { SiteFooter } from "@/components/site-footer"
import { BottomNav } from "@/components/bottom-nav"
import { MOBILE_BOTTOM_CLEARANCE } from "@/lib/layout-constants"
import { AIChatWidget } from "@/components/ai-chat-widget"
import { PageView } from "@/components/analytics/page-view"
import { routing } from "@/i18n/routing"
import { siteUrl } from "@/lib/seo"
import { notFound } from "next/navigation"
import type { ReactNode } from "react"

type Props = {
  children: ReactNode
  params: Promise<{ locale: string }>
}

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }))
}

/**
 * Site-wide metadata defaults, per locale. Pages that set their own title /
 * description override these; pages that don't (and every og/twitter card
 * without page-level values) inherit the right language instead of English.
 */
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params
  const t = await getTranslations({ locale, namespace: "siteMeta" })
  const isEs = locale === "es"
  return {
    title: {
      default: t("titleDefault"),
      template: t("titleTemplate"),
    },
    description: t("description"),
    keywords: t("keywords").split(",").map((k) => k.trim()).filter(Boolean),
    openGraph: {
      title: t("ogTitle"),
      description: t("ogDescription"),
      url: isEs ? `${siteUrl}/es` : siteUrl,
      siteName: "Lompoc Locals",
      locale: isEs ? "es_US" : "en_US",
      alternateLocale: isEs ? ["en_US"] : ["es_US"],
      type: "website",
      // Social share cover generated by app/opengraph-image.tsx (branded).
    },
    twitter: {
      card: "summary_large_image",
      title: t("ogTitle"),
      description: t("twitterDescription"),
    },
  }
}

export default async function LocaleLayout({ children, params }: Props) {
  const { locale } = await params

  if (!routing.locales.includes(locale as "en" | "es")) {
    notFound()
  }

  const messages = await getMessages()

  return (
    <NextIntlClientProvider locale={locale} messages={messages}>
      <SiteHeader />
      <main className={`flex-1 pt-16 ${MOBILE_BOTTOM_CLEARANCE}`}>{children}</main>
      <SiteFooter />
      <BottomNav />
      <AIChatWidget />
      <PageView />
      <Toaster />
    </NextIntlClientProvider>
  )
}
