#!/usr/bin/env python3
"""COMING HOME — Fri Sep 18 2026. Napoleon Kaufman, Lompoc High class of 1990, first-round pick
and six seasons with the Raiders, returns to Huyck Stadium tonight as Dublin's head coach.
A vertical TIMELINE animation (new grammar for us): the line draws down through three stops.
Typography + our own Huyck photography only — no photos of him, nothing we don't own.
23.0 s, 9:16. Cillian read, cinematic bed. Generated by: python3 gen.py
"""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
X = 0.28
SCENES = [("s1-open", 0.00, 4.60), ("s2-name", 4.40, 2.30), ("s3-line", 6.50, 13.10), ("s4-home", 19.40, 4.00)]
TOTAL = 23.40
VO_START = 0.50; VO_DUR = 22.10
SUBS = [
    (0.50, 3.60,  "Tonight, a Lompoc kid comes home."),
    (4.03, 5.40,  "Napoleon Kaufman."),
    (5.93, 8.30,  "Lompoc High, class of 1990."),
    (8.75, 11.60, "5,151 yards."),
    (11.97, 13.40, "86 touchdowns."),
    (13.78, 14.90, "A first-round pick."),
    (15.25, 16.95, "Six seasons with the Raiders."),
    (17.49, 20.60, "Tonight he coaches Dublin, back at Huyck Stadium."),
    (21.15, 22.60, "Welcome home, Coach."),
]
GOLD = "#efc618"; INK = "#241629"; PURPLE = "#650c75"; BG = "#0e0a12"; CREAM = "#f2ead9"
STOPS = [
    ("1990", "LOMPOC HIGH",   "5,151 yards · 86 touchdowns"),
    ("1995", "FIRST-ROUND PICK", "Six seasons · Oakland Raiders"),
    ("2026", "HEAD COACH, DUBLIN", "Back at Huyck tonight"),
]

def css(cid):
    return f"""
      [data-composition-id="{cid}"] .stage {{ position:absolute; inset:0; opacity:0; will-change:opacity; }}
      [data-composition-id="{cid}"] .vig {{ position:absolute; inset:0; z-index:30; pointer-events:none; background:radial-gradient(ellipse 100% 82% at 50% 45%, rgba(8,6,10,0) 58%, rgba(8,6,10,0.62) 100%); }}
      [data-composition-id="{cid}"] .grain {{ position:absolute; inset:0; pointer-events:none; opacity:0.08; z-index:50; background-image:url("data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 width=%27200%27 height=%27200%27%3E%3Cfilter id=%27n%27%3E%3CfeTurbulence type=%27fractalNoise%27 baseFrequency=%270.9%27 numOctaves=%272%27/%3E%3C/filter%3E%3Crect width=%27200%27 height=%27200%27 filter=%27url(%23n)%27 opacity=%271%27/%3E%3C/svg%3E"); }}
      [data-composition-id="{cid}"] .mark {{ position:absolute; top:150px; right:84px; width:92px; height:auto; z-index:44; }}
      [data-composition-id="{cid}"] .cover {{ position:absolute; inset:0; width:100%; height:100%; object-fit:cover; display:block; }}
      [data-composition-id="{cid}"] .scrim {{ position:absolute; inset:0; z-index:31; pointer-events:none; background:linear-gradient(to top, rgba(14,10,18,0.96) 0%, rgba(14,10,18,0.68) 40%, rgba(14,10,18,0.22) 72%); }}
      [data-composition-id="{cid}"] .kicker {{ color:{GOLD}; font-weight:800; font-size:30px; letter-spacing:7px; text-transform:uppercase; }}
      [data-composition-id="{cid}"] .hero {{ color:#fff; font-weight:800; line-height:0.96; letter-spacing:-4px; text-shadow:0 8px 34px rgba(8,6,10,0.75); }}
    """

def wrap(cid, dur, inner, js, first=False):
    fade = (f'tl.set("#{cid}-stage", {{ autoAlpha:1 }}, 0);' if first
            else f'tl.fromTo("#{cid}-stage", {{ autoAlpha:0 }}, {{ autoAlpha:1, duration:{X}, ease:"power1.inOut" }}, 0);')
    return f'''<template>
  <div data-composition-id="{cid}" data-width="1080" data-height="1920" data-duration="{dur:.2f}" style="position:absolute; inset:0; overflow:hidden; background:{BG if first else 'transparent'}">
    <style>{css(cid)}
    </style>
    <div class="stage" id="{cid}-stage"{' style="opacity:1"' if first else ''}>
      {inner}
      <div class="vig"></div>
    </div>
    <img class="mark" src="public/mark-white.png" alt="" />
    <div class="grain"></div>
    <script>
      (() => {{
        const tl = gsap.timeline({{ paused:true, defaults:{{ ease:"power3.out", duration:0.5 }} }});
        {fade}
        {js}
        tl.set({{}}, {{}}, {dur:.2f});
        window.__timelines["{cid}"] = tl;
      }})();
    </script>
  </div>
</template>
'''

def count_js(sel, target, at, dur=2.2, comma=True):
    fmt = 'String(Math.round(o.v)).replace(/\\B(?=(\\d{3})+(?!\\d))/g, ",")' if comma else 'String(Math.round(o.v))'
    return (f'{{ const o={{v:0}}; const el=document.querySelector("{sel}"); '
            f'tl.to(o, {{ v:{target}, duration:{dur:.2f}, ease:"power2.out", onUpdate:()=>{{ el.textContent = {fmt}; }} }}, {at:.2f}); }}')

def scene_html(cid, dur):
    if cid == "s1-open":
        inner = f'''<img class="cover" src="public/huyck-stadium.jpg" alt="" style="filter:brightness(0.44) saturate(0.85)" />
      <div class="scrim"></div>
      <div style="position:absolute; left:84px; top:300px; z-index:36"><span class="kicker" id="{cid}-k" style="opacity:1">Tonight at Huyck</span></div>
      <div style="position:absolute; left:84px; right:84px; bottom:26%; z-index:36">
        <span class="hero" id="{cid}-h" style="display:block; font-size:118px; opacity:1">A LOMPOC KID<br />COMES HOME</span>
      </div>'''
        js = (f'tl.fromTo("#{cid}-h", {{ scale:1.05 }}, {{ scale:1, duration:2.6, ease:"power2.out" }}, 0);'
              f'tl.fromTo("#{cid}-k", {{ autoAlpha:0, y:-8 }}, {{ autoAlpha:1, y:0, duration:0.4 }}, 0.05);')
        return wrap(cid, dur, inner, js, first=True)
    if cid == "s2-name":
        inner = f'''<div style="position:absolute; inset:0; background:linear-gradient(180deg,#151019 0%, {BG} 100%)"></div>
      <div style="position:absolute; left:84px; right:84px; top:38%; z-index:36">
        <span class="kicker" id="{cid}-k" style="display:block; opacity:0">Lompoc High · Class of 1990</span>
        <span class="hero" id="{cid}-n" style="display:block; margin-top:26px; font-size:104px; opacity:0">NAPOLEON<br />KAUFMAN</span>
        <div id="{cid}-rule" style="height:6px; background:{GOLD}; margin-top:34px; transform-origin:0 50%; border-radius:3px"></div>
      </div>'''
        js = (f'tl.fromTo("#{cid}-n", {{ autoAlpha:0, y:26 }}, {{ autoAlpha:1, y:0, duration:0.5, ease:"expo.out" }}, 0.10);'
              f'tl.fromTo("#{cid}-k", {{ autoAlpha:0 }}, {{ autoAlpha:1, duration:0.35 }}, 0.45);'
              f'tl.fromTo("#{cid}-rule", {{ scaleX:0 }}, {{ scaleX:1, duration:0.7, ease:"power3.inOut" }}, 0.55);')
        return wrap(cid, dur, inner, js)
    if cid == "s3-line":
        top0, gap = 480, 400
        rows = []
        for i, (yr, ttl, sub) in enumerate(STOPS):
            y = top0 + i * gap
            statline = sub
            if i == 0:
                statline = f'<span id="{cid}-y" style="font-variant-numeric:tabular-nums">0</span> yards · <span id="{cid}-t" style="font-variant-numeric:tabular-nums">0</span> touchdowns'
            rows.append(f'''<div id="{cid}-s{i}" style="position:absolute; left:250px; right:84px; top:{y}px; z-index:38; opacity:0">
          <span style="display:block; color:{GOLD}; font-weight:800; font-size:44px; letter-spacing:4px">{yr}</span>
          <span style="display:block; margin-top:8px; color:#fff; font-weight:800; font-size:60px; letter-spacing:-1.5px; line-height:1.02">{ttl}</span>
          <span style="display:block; margin-top:12px; color:rgba(242,234,217,0.78); font-weight:600; font-size:36px">{statline}</span>
        </div>
        <div id="{cid}-d{i}" style="position:absolute; left:151px; top:{y+18}px; width:28px; height:28px; border-radius:50%; background:{GOLD}; box-shadow:0 0 22px rgba(239,198,24,0.8); z-index:39; opacity:0"></div>''')
        line_h = (len(STOPS) - 1) * gap + 30
        inner = f'''<div style="position:absolute; inset:0; background:linear-gradient(180deg,{BG} 0%, #15101b 60%, {BG} 100%)"></div>
      <div id="{cid}-rail" style="position:absolute; left:163px; top:{top0+18}px; width:4px; height:{line_h}px; background:linear-gradient(180deg,{GOLD},rgba(239,198,24,0.25)); transform-origin:50% 0%; z-index:37"></div>
      {"".join(rows)}'''
        js = [f'tl.fromTo("#{cid}-rail", {{ scaleY:0 }}, {{ scaleY:1, duration:{dur-2.0:.2f}, ease:"none" }}, 0.30)']
        ats = [0.30, 7.15, 11.00]
        for i, at in enumerate(ats):
            js.append(f'tl.fromTo("#{cid}-d{i}", {{ autoAlpha:0, scale:0.2 }}, {{ autoAlpha:1, scale:1, duration:0.34, ease:"back.out(2.4)" }}, {at:.2f});')
            js.append(f'tl.fromTo("#{cid}-s{i}", {{ autoAlpha:0, x:26 }}, {{ autoAlpha:1, x:0, duration:0.46, ease:"expo.out" }}, {at+0.10:.2f});')
        js.append(count_js(f"#{cid}-y", 5151, 2.10, 2.60))
        js.append(count_js(f"#{cid}-t", 86, 5.40, 1.20, comma=False))
        return wrap(cid, dur, inner, "\n        ".join(js))
    if cid == "s4-home":
        inner = f'''<img class="cover" src="public/huyck-goalposts.jpg" alt="" style="filter:brightness(0.42) saturate(0.9)" />
      <div class="scrim"></div>
      <div style="position:absolute; left:0; right:0; top:30%; z-index:36; text-align:center">
        <span class="hero" id="{cid}-h" style="display:block; font-size:104px; opacity:0">Welcome home,<br />Coach.</span>
        <span id="{cid}-info" style="display:block; margin-top:36px; color:{GOLD}; font-weight:800; font-size:50px; letter-spacing:-0.5px; opacity:0">Braves vs Dublin · 7:00 PM</span>
        <span id="{cid}-pill" style="display:inline-block; margin-top:40px; background:{GOLD}; color:{INK}; font-weight:800; font-size:40px; padding:18px 34px; border-radius:999px; opacity:0">lompoclocals.com/football</span>
      </div>'''
        js = (f'tl.fromTo("#{cid}-h", {{ autoAlpha:0, y:22 }}, {{ autoAlpha:1, y:0, duration:0.55, ease:"expo.out" }}, 0.20);'
              f'tl.fromTo("#{cid}-info", {{ autoAlpha:0, y:14 }}, {{ autoAlpha:1, y:0, duration:0.4 }}, 1.10);'
              f'tl.fromTo("#{cid}-pill", {{ autoAlpha:0, y:14, scale:0.95 }}, {{ autoAlpha:1, y:0, scale:1, duration:0.45, ease:"back.out(1.4)" }}, 2.30);')
        return wrap(cid, dur, inner, js)
    raise ValueError(cid)

def subs_scene():
    cid = "subs"
    items = "".join(f'\n      <div class="sub" id="sub-{i}"><span>{t}</span></div>' for i, (_, _, t) in enumerate(SUBS))
    js = ",\n          ".join(f"[{a:.2f}, {b:.2f}]" for a, b, _ in SUBS)
    return f'''<template>
  <div data-composition-id="{cid}" data-width="1080" data-height="1920" data-duration="{TOTAL:.2f}" style="position:absolute; inset:0; overflow:hidden; background:transparent; pointer-events:none">
    <style>
      [data-composition-id="{cid}"] .wrapz {{ position:absolute; left:60px; right:60px; bottom:310px; z-index:70; display:flex; justify-content:center; }}
      [data-composition-id="{cid}"] .sub {{ position:absolute; left:0; right:0; bottom:0; display:flex; justify-content:center; opacity:0; }}
      [data-composition-id="{cid}"] .sub span {{ display:inline-block; max-width:920px; background:rgba(0,0,0,0.66); color:#fff; font-weight:600; font-size:42px; line-height:1.25; padding:14px 28px; border-radius:20px; text-align:center; }}
    </style>
    <div class="wrapz" data-layout-allow-overlap>{items}
    </div>
    <script>
      (() => {{
        const S = [
          {js}
        ];
        const tl = gsap.timeline({{ paused:true }});
        S.forEach(([a,b], i) => {{
          tl.fromTo("#sub-"+i, {{ autoAlpha:0, y:10 }}, {{ autoAlpha:1, y:0, duration:0.13 }}, a);
          tl.to("#sub-"+i, {{ autoAlpha:0, duration:0.11 }}, b-0.11);
        }});
        tl.set({{}}, {{}}, {TOTAL:.2f});
        window.__timelines["{cid}"] = tl;
      }})();
    </script>
  </div>
</template>
'''

def progress_scene():
    cid = "progress"
    return f'''<template>
  <div data-composition-id="{cid}" data-width="1080" data-height="1920" data-duration="{TOTAL:.2f}" style="position:absolute; inset:0; overflow:hidden; background:transparent; pointer-events:none">
    <style>[data-composition-id="{cid}"] .bar {{ position:absolute; left:0; right:0; bottom:0; height:8px; background:{GOLD}; transform-origin:0% 50%; transform:scaleX(0); z-index:70; box-shadow:0 0 12px rgba(239,198,24,0.6); }}</style>
    <div class="bar" id="prog-bar"></div>
    <script>(() => {{ const tl = gsap.timeline({{paused:true}}); tl.fromTo("#prog-bar", {{scaleX:0}}, {{scaleX:1, duration:{TOTAL:.2f}, ease:"none"}}, 0); window.__timelines["{cid}"] = tl; }})();</script>
  </div>
</template>
'''

def index_html():
    rows = [f'      <div id="el-{c}" data-composition-id="{c}" data-composition-src="compositions/{c}.html" data-start="{s:.2f}" data-duration="{d:.2f}" data-track-index="{i+1}"></div>' for i,(c,s,d) in enumerate(SCENES)]
    n = len(SCENES)
    rows.append(f'      <div id="el-subs" data-composition-id="subs" data-composition-src="compositions/subs.html" data-start="0" data-duration="{TOTAL:.2f}" data-track-index="{n+1}"></div>')
    rows.append(f'      <div id="el-progress" data-composition-id="progress" data-composition-src="compositions/progress.html" data-start="0" data-duration="{TOTAL:.2f}" data-track-index="{n+2}"></div>')
    a0 = n + 3
    auto = '{"version": 1, "lanes": [{"target": "volume", "points": [{"t": 0, "v": 0}, {"t": 0.6, "v": 0.26}, {"t": %.2f, "v": 0.26}, {"t": %.2f, "v": 0}]}]}' % (TOTAL-1.4, TOTAL)
    return f'''<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1080, height=1920" />
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>
    <style>
      * {{ margin:0; padding:0; box-sizing:border-box; }}
      @font-face {{ font-family:"Plus Jakarta Sans"; src:url("public/fonts/plus-jakarta-sans-latin.woff2") format("woff2"); font-weight:200 800; font-style:normal; }}
      html, body {{ margin:0; width:1080px; height:1920px; overflow:hidden; background:{BG}; }}
      body {{ font-family:"Plus Jakarta Sans", sans-serif; }}
      #root {{ position:relative; width:1080px; height:1920px; overflow:hidden; }}
      #root > div[data-composition-src] {{ position:absolute; inset:0; }}
    </style>
  </head>
  <body>
    <!-- COMING HOME — Napoleon Kaufman returns to Huyck as Dublin's head coach, Fri Sep 18 2026.
         Facts: Lompoc High '90 (5,151 yds, 86 TD), 1995 first-round pick, 6 seasons Raiders, Dublin HC since 2024.
         Typography + our own Huyck photos only. Generated by gen.py. -->
    <div id="root" data-composition-id="main" data-start="0" data-duration="{TOTAL:.2f}" data-width="1080" data-height="1920">
{chr(10).join(rows)}

      <audio id="vo" class="clip" data-audio-group="voiceover" src="public/vo.wav" data-start="{VO_START:.2f}" data-media-start="0" data-duration="{VO_DUR:.2f}" data-track-index="{a0}" data-volume="0.76" data-fade-in="0.05" data-fade-out="0.12"></audio>
      <audio id="music-bed" class="clip" data-audio-group="music" src="public/bed.wav" data-start="0" data-media-start="0" data-duration="{TOTAL:.2f}" data-track-index="{a0+1}" data-volume="0.26" data-fade-in="0.6" data-fade-out="1.4" data-automation='{auto}' data-fx-carve='{{"enabled":true,"sources":["voiceover"],"strength":0.55}}'></audio>
      <audio id="sfx-1" class="clip" data-audio-group="sfx" src="public/whoosh.wav" data-start="4.40" data-media-start="0" data-duration="1.20" data-track-index="{a0+2}" data-volume="0.20" data-fade-out="0.3"></audio>
      <audio id="sfx-2" class="clip" data-audio-group="sfx" src="public/shield-hit.wav" data-start="19.40" data-media-start="0" data-duration="1.40" data-track-index="{a0+2}" data-volume="0.24" data-fade-out="0.4"></audio>
    </div>
    <script>window.__timelines["main"] = gsap.timeline({{ paused:true }});</script>
  </body>
</html>
'''

os.makedirs(os.path.join(HERE, "compositions"), exist_ok=True)
for c, s, d in SCENES:
    open(os.path.join(HERE, f"compositions/{c}.html"), "w").write(scene_html(c, d))
open(os.path.join(HERE, "compositions/subs.html"), "w").write(subs_scene())
open(os.path.join(HERE, "compositions/progress.html"), "w").write(progress_scene())
open(os.path.join(HERE, "index.html"), "w").write(index_html())
print("wrote", [s[0] for s in SCENES])
